### ISSUE TITLE
Unwrap does not read from the socket again

### ISSUE THREAD

**Issue by indvamshi** [alkarn/sslengine.example#2]
Hi
I have gone through the code and I found that buffer underflow does not read the from the socket again. It only increases the buffer size.
Based on the documentation
https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngine.html
If the client reads partial data from the network, we need to force the client to read it again. But, its not happening with your code.

After debugging the code, when I force the logic to go into buffer underflow I get the following exception 
Exception in thread "main" javax.net.ssl.SSLException: Unsupported record version Unknown-0.0
	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:117)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:862)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:775)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)

Because the data read initially is reset in buffer underflow.

Can you please look into this if you have time.

Much appreciated.
Thanks
Vam

**Comment by alexbokos** [comment]
Hello Vam,

first of all thanks for using the code!

Can you provide the steps to reproduce the problem and create the exception?

**Comment by indvamshi** [comment]
Thanks for responding.

It usually happens when read method reads partial data from the socket.
Initially I found this issue when am doing stress testing like 20 threads
with ramp up 10 and continue for ever.

Let me know if you need more information.

**Comment by abmangroliya15** [comment]
Thanks for code. I'm using your code to build server but getting same issue. can you please help me to resolve this issue?

**Comment by smadappa** [comment]
@indvamshi @alkarn I am having same issue where large items fail with "javax.net.ssl.SSLException: Unsupported record version Unknown-0.0". Can you please let me know if you have solved this issue or if you chose an alternative solution?

**Comment by kirtisinghvliv** [comment]
@alkarn @indvamshi I am facing same issue with large amount of data.  can you help me please to resolve issue?

**Comment by JerryChin** [comment]
@kirtisinghvliv Why don't you use Netty ? This project is not very appropriate for serious project.

**Comment by ajithberlin** [comment]
@alkarn facing the same issue any solution on this?

**Comment by marianobarrios** [comment]
FYI: Partially inspired by this project, I wrote [this other one](https://github.com/marianobarrios/tls-channel), with a very similar goal. Leaving this here in case it is of use.

**Comment by Ajith1406** [comment]
> @alkarn facing the same issue any solution on this?

This was solved after I increased buffer size little more to peerNetApp buffer

**Comment by Ajith1406** [comment]
> FYI: Partially inspired by this project, I wrote [this other one](https://github.com/marianobarrios/tls-channel), with a very similar goal. Leaving this here in case it is of use.

thanks @marianobarrios your code really helped a lot
